name: Build and deploy app

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: build-and-deploy

permissions: {}

jobs:
  build:
    name: Build the container image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the container image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/williamjacksn/birthdayfeed:latest
      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: Push latest image to registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          push: true
          tags: ghcr.io/williamjacksn/birthdayfeed:latest
  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Deploy the app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Deploy the app
        run: sh ci/ssh-deploy.sh
        env:
          SSH_HOST: ${{ secrets.ssh_host }}
          SSH_PRIVATE_KEY: ${{ secrets.ssh_private_key }}
          SSH_USER: ${{ secrets.ssh_user }}
